package com.library_stock.library_stock.config;

import com.library_stock.library_stock.book.Book;
import com.library_stock.library_stock.book.BookRepository;
import com.library_stock.library_stock.bookInstance.BookInstance;
import com.library_stock.library_stock.bookInstance.BookInstanceRepository;
import com.library_stock.library_stock.bookInstance.types.BookStatus;
import com.library_stock.library_stock.location.Location;
import com.library_stock.library_stock.location.LocationRepository;
import com.library_stock.library_stock.user.User;
import com.library_stock.library_stock.user.UserRepository;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDateTime;

@Configuration
public class DatabaseSeeder {

    @Bean
    CommandLineRunner initDatabase(
            BookRepository bookRepository,
            BookInstanceRepository bookInstanceRepository,
            LocationRepository locationRepository,
            UserRepository userRepository,
            PasswordEncoder passwordEncoder
    ) {
        return args -> {

            // ===========================================
            // USER - BRUNO LOPES
            // ===========================================
            userRepository.findByCpf("01234567890")
                    .orElseGet(() -> {
                        User bruno = new User(
                                0,
                                "01234567890",
                                passwordEncoder.encode("12345678"),
                                "Bruno Lopes",
                                "bruno@example.com"
                        );
                        return userRepository.save(bruno);
                    });

            // ===========================================
            // BOOKS + INSTANCES (50 livros)
            // ===========================================

            String[] titles = {
                    "The Silent River", "Echoes of Eternity", "Broken Skies", "The Last Kingdom",
                    "Dreams of Tomorrow", "Crimson Shadows", "Emerald Dawn", "Lost Horizons",
                    "Burning Fate", "The Forgotten Path", "Winds of Winter", "Voices in the Dark",
                    "Shattered Realms", "Beyond the Stars", "The Iron Throne", "A Whisper of Hope",
                    "Fading Memories", "The Crystal Empire", "Ashes of War", "Hidden Truths",
                    "Rise of Legends", "Stormborn", "Threads of Destiny", "The Final Voyage",
                    "Moonlit Promise", "The Blood Oath", "Frostbound", "Chasing Infinity",
                    "Shadowfall", "The Lost Archive", "Requiem of Souls", "Golden Horizon",
                    "The Witch’s Secret", "Blades of Honor", "Fragments of Light", "The Eternal Maze",
                    "Frozen Echoes", "The Black Sun", "Sands of Time", "The Lone Wolf",
                    "Children of Fire", "The Hidden Fortress", "The Fallen Star", "Rising Sun",
                    "Tides of Magic", "The Last Oracle", "Broken Destiny", "A World Apart",
                    "The Iron Moon", "Secrets of the Deep"
            };

            String[] authors = {
                    "John Smith", "Anna Gray", "Lucas Turner", "Amelia Clark",
                    "Robert Hill", "Sophie Adams", "Daniel Carter", "Emily Stone"
            };

            String[] publishers = {
                    "HarperCollins", "Penguin Books", "Random House", "Simon & Schuster"
            };

            for (int i = 0; i < 50; i++) {

                String isbn = "978000000" + String.format("%04d", i + 1);

                // Cria o livro SE não existir
                int finalI = i;
                Book createdBook = bookRepository.findByIsbn(isbn)
                        .orElseGet(() -> bookRepository.save(
                                new Book(
                                        0,
                                        titles[finalI],
                                        authors[finalI % authors.length],
                                        publishers[finalI % publishers.length],
                                        isbn,
                                        "Fiction",
                                        "Autogenerated description for " + titles[finalI]
                                )
                        ));

                // Criando uma localização aleatória
                String code = "S" + (i % 10 + 1) + "-A" + (i % 5 + 1) + "-L" + (i % 3 + 1) + "-P" + (i % 4 + 1);

                int finalI1 = i;
                Location loc = locationRepository.findByClassificationCode(code)
                        .orElseGet(() -> locationRepository.save(
                                new Location(
                                        0,
                                        "Sector " + (finalI1 % 10 + 1),
                                        "Aisle " + (finalI1 % 5 + 1),
                                        "Shelf " + (finalI1 % 3 + 1),
                                        "Level " + (finalI1 % 4 + 1),
                                        "Pos " + (finalI1 % 8 + 1),
                                        code
                                )
                        ));

                // Criando 1 instância por livro
                String internalCode = "INT-" + String.format("%04d", i + 1);

                if (bookInstanceRepository.findByInternalCode(internalCode).isEmpty()) {
                    bookInstanceRepository.save(
                            new BookInstance(
                                    0,
                                    internalCode,
                                    LocalDateTime.now(),
                                    "Good",
                                    BookStatus.AVAILABLE,
                                    createdBook,
                                    loc
                            )
                    );
                }
            }

            System.out.println("==== 50 BOOKS + INSTANCES SEEDED ====");
        };
    }
}